### PR TITLE
Ops manages python modules using yum

### PR DESCRIPTION
**Pull request by dak1n1**
To help keep our systems consistent, manage modules using yum.

### CODE REVIEW

**Comment by dak1n1** [comment]
Tested in free-int. It works!

**Comment by dak1n1** [comment]
```
[root@free-int-master-3c664 ~]# oc get pods -n openshift-infra
NAME                                READY     STATUS    RESTARTS   AGE
analytics-23-w7rk9                  1/1       Running   0          4d
hawkular-cassandra-1-565bl          1/1       Running   0          4d
hawkular-cassandra-2-nknj9          1/1       Running   0          4d
hawkular-cassandra-3-6kb8d          1/1       Running   0          4d
hawkular-metrics-vrpv2              1/1       Running   0          4d
heapster-ltnsb                      1/1       Running   0          4d
hibernation-26-6tr5t                1/1       Running   0          4d
online-console-extensions-1-build   0/1       Error     0          1m

[root@free-int-master-3c664 ~]# oc logs online-console-extensions-1-build -n openshift-infra
Pulling image "online-console-extensions-builder:latest" ...
pulling image error : Error: image library/online-console-extensions-builder:latest not found
error: build error: unable to get online-console-extensions-builder:latest
```

**Comment by damemi** [comment]
@dak1n1 could that error have something to do with our custom httpd builder? We use that to copy the files from the right environment directory in the git repo to a common folder in the apache image (for consistency in the url's we're serving) so if it's not found that would cause an issue

**Comment by dak1n1** [comment]
This is the line causing the above error:

`ansible/roles/oso_console_extensions/defaults/main.yml:osce_builder_image: 'online-console-extensions-builder:latest'`

It doesn't specify a full path to the image, so by default it's looking in `library`, which doesn't exist. It's unrelated to this PR.

**Review by damemi — APPROVED** [review]

**Pull request merged**
